name:                elminator
version:             0.2.3.0
git:                 "https://github.com/sras/elminator.git"
license:             BSD3
author:              "Sandeep.C.R"
maintainer:          "sandeep@sras.me"
copyright:           "2019 Sandeep.C.R"
category:            Code Generation, Elm
synopsis:            Generate ELM types/encoders/decoders from Haskell types.

extra-source-files:
- README.md
- ChangeLog.md

ghc-options: -Wall

description:         Please see the README on GitHub at <https://github.com/sras/elminator#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- containers
- text
- mtl
- aeson

library:
  source-dirs: src
  exposed-modules:
    - Elminator
  other-modules:
    - Elminator.Generics.Simple
    - Elminator.ELM.Elm19
    - Elminator.ELM.Elm18
    - Elminator.ELM.Generator
    - Elminator.ELM.Render
    - Elminator.Lib

tests:
  elminator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elminator
